CREATE TABLE marketplace_statistics ( -- TODO it's just example generated by ai think about your own table name, structure and columns
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    statistics_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_marketplace_statistics_timestamp ON marketplace_statistics(statistics_timestamp);
