package by.fnx.market.analyzer.repository.postgres;

import java.time.Instant;

import by.fnx.market.analyzer.repository.MarketPlaceStatisticsRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.ResultSetExtractor;
import org.springframework.stereotype.Repository;

@Repository
@RequiredArgsConstructor
public class PostgresMarketPlaceStatisticsRepository implements MarketPlaceStatisticsRepository {

    private final JdbcTemplate jdbcTemplate;

    @Override
    public boolean isStatisticsAvailableByTimestamp(Instant instant) {
        // TODO it's example generated by AI, please implement your own logic
        return Boolean.TRUE.equals(jdbcTemplate.query(
            "SELECT 1 FROM marketplace_statistics WHERE statistics_timestamp = ?",
            ps -> ps.setObject(1, instant),
            (ResultSetExtractor<Boolean>) rs -> rs.next()
        ));
    }

    // TODO add other method if you need any
}
